## Objective of this course

   * learn basic of python
   

## list of topics - session 02
   
       - 1. What is python?
       - 2. Why Python?
       - 3. Get started
       - 4. Primitive datatypes
       - 5. Data structures
       - 6. Operators
       - 7. Conditional Statement - if, elif and else
       - 8. Iterations - while, for loop   

## 5.3 Dictionaries

    * A dictionary is a mapping data structure
    
    * It establishes a relationship between a key and a value, and maps each key to some value
    
    * Map keys to values through index
    
    * Suitable for unstructured data
    
    * For instance, think about capitals as a dictionary, which uses a country name as key.  The capitals dictionary would map 'Belgium' to 'Brussels’ and ‘France’ to ‘Paris’.

    * Handy to store data organized by name, rather than position:
    * Concept index of a book on programming. (‘for loop’ on ‘pages 10-15’)
    * Contacts in your phone (person to phone number)
    * Temperature records for each city of a country (city name to temperature 


### 5.3.1 Basics: Creating a dictionary

### Dictionaries can be defined in two ways:

    * Notation that uses curly brackets: { and }
    * Notation that uses the built-in function dict()
 

In [65]:
landcover = {} # the empty dictionary

In [66]:
landcover["Natural grasses"] = 45
landcover["Agricultural grasses"] = 1 
landcover["Deciduous"] = 11 
landcover["Coniferous"] =12

#### Now, we can take a look at its structure by printing the whole dictionary

In [67]:
print(landcover)

{'Natural grasses': 45, 'Agricultural grasses': 1, 'Deciduous': 11, 'Coniferous': 12}


In [68]:
type(landcover)

dict

In [106]:
dict1= {}
type(dict1)

dict

In [102]:
dict1['001'] = 'Amuthan'

In [103]:
dict1

{'001': 'Amuthan'}

### An element is accessed using its key:

In [69]:
landcover["Coniferous"]

12

In [70]:
landcover["Natural grasses"]

45

In [71]:
landcover["Natural"]

KeyError: 'Natural'

In [73]:
landcover.keys()

dict_keys(['Natural grasses', 'Agricultural grasses', 'Deciduous', 'Coniferous'])

In [74]:
landcover.values()

dict_values([45, 1, 11, 12])

In [75]:
landcover.items()

dict_items([('Natural grasses', 45), ('Agricultural grasses', 1), ('Deciduous', 11), ('Coniferous', 12)])

In [76]:
landcover[1] = 10

In [13]:
'name' in landcover.keys()

False

### 5.3.2 Keys 

    * Dictionaries store key:value pairs
    * Keys must be immutable
    
#### Types of key:

    * Number.
    * String.
    * Tuple.


In [77]:
string = "Hello"
string[0] = "J"
print(string)


TypeError: 'str' object does not support item assignment

In [81]:
landcover[1.1] = 10

In [82]:
landcover[1] = 10

In [83]:
print(landcover)

{'Natural grasses': 45, 'Agricultural grasses': 1, 'Deciduous': 11, 'Coniferous': 12, 1: 10, 1.1: 10}


In [84]:
landcover[[1,3, 2]] = 3

TypeError: unhashable type: 'list'

In [85]:
landcover[(1,3, 2)] = 3

In [86]:
landcover[{1,3, 2}] = 3

TypeError: unhashable type: 'set'

#### * Number : 

In [87]:
landcover[45] = "Natural grasses"
print(landcover)

{'Natural grasses': 45, 'Agricultural grasses': 1, 'Deciduous': 11, 'Coniferous': 12, 1: 10, 1.1: 10, (1, 3, 2): 3, 45: 'Natural grasses'}


###### * String: 

In [135]:
landcover["Natural grasses"] = 45
print(landcover)

{'Agriculture': 1, 'Coniferous': 12, 'Deciduous': 11, 'Grasses': 45, 45: 'Natural grasses', 'Natural grasses': 45}


###### * Tuple : 

In [136]:
landcover[("Enschede", "52N","3E")] = 45
print(landcover)

{'Agriculture': 1, 'Coniferous': 12, 'Deciduous': 11, 'Grasses': 45, 45: 'Natural grasses', 'Natural grasses': 45, ('Enschede', '52N', '3E'): 45}


#### But a key cannot be a list:

In [138]:
landcover[["Enschede", "latitude", "longitude"]] = 45
print(landcover) # TypeError: unhashable type: ‘list’

TypeError: unhashable type: 'list'

### 5.3.3 Values

    * Values can be anything!
    * If Enschede municipality has multiple land covers, we can store them all:

In [14]:
landcover["Enschede"] = ("Coniferous", "Built-up", "Agricultural grasses", "Orchard", "Reed")
print(landcover)

{'Natural grasses': 45, 'Agricultural grasses': 1, 'Deciduous': 11, 'Coniferous': 12, 45: 'Natural grasses', ('Enschede', '52N', '3E'): 45, 'Enschede': ('Coniferous', 'Built-up', 'Agricultural grasses', 'Orchard', 'Reed')}


#### Here as a tuple; could also have been a list

### We can build our dictionary using the built-in dict() function:

In [16]:
landcover = dict()
print(landcover)

{}


In [17]:
mixed_forest = ("Coniferous", "Deciduous")
landcover["Hengelo"] = mixed_forest
landcover["Amsterdam"] = ("Build-up", "Greenhouse ")

In [18]:
print(landcover)

{'Hengelo': ('Coniferous', 'Deciduous'), 'Amsterdam': ('Build-up', 'Greenhouse ')}


In [21]:
mixed_forest = ("Coniferous", "Deciduous") 
urban_area = ("Built-up", "Greenhouses")
landcover = dict(Veluwe = mixed_forest, Amsterdam = urban_area)

In [22]:
print(landcover)

{'Veluwe': ('Coniferous', 'Deciduous'), 'Amsterdam': ('Built-up', 'Greenhouses')}


### 5.3.4 Dictionary methods

##### Similar to lists and strings, dictionary methods are called like:
##### object.method()

### Important methods:
    
    * .keys(): returns the list of all keys
    * .values(): returns the list of all values
    * .items(): returns the (key,value) pairs as a list

In [38]:
landcover = {"Agriculture": 1, "Coniferous": 12, "Deciduous": 11, "Grasses": 45}
print(landcover.keys())

dict_keys(['Agriculture', 'Coniferous', 'Deciduous', 'Grasses'])


In [39]:
print(landcover.values())

dict_values([1, 12, 11, 45])


In [40]:
print(landcover.items())

dict_items([('Agriculture', 1), ('Coniferous', 12), ('Deciduous', 11), ('Grasses', 45)])


## Updating a dictionary

##### Changing values:

In [41]:
landcover["Agriculture"] = 999

In [42]:
landcover["Grasses"] = 13

In [43]:
print(landcover)

{'Agriculture': 999, 'Coniferous': 12, 'Deciduous': 11, 'Grasses': 13}


## Populating a dictionary with the items of another dictionary:

In [107]:
new_landcovers = {"Reed": 36, "Greenhouse": 20} 
landcover.update(new_landcovers) 
print(landcover)

{'Natural grasses': 45, 'Agricultural grasses': 1, 'Coniferous': 12, 1.1: 10, (1, 3, 2): 3, 45: 'Natural grasses', 'Greenhouse': 20, 'Reed': 36}


In [108]:
new_landcovers1 = {"Reed": 76} 
landcover.update(new_landcovers1) 
print(landcover)

{'Natural grasses': 45, 'Agricultural grasses': 1, 'Coniferous': 12, 1.1: 10, (1, 3, 2): 3, 45: 'Natural grasses', 'Greenhouse': 20, 'Reed': 76}


In [109]:
landcover['Reed'] = 786

In [110]:
print(landcover)

{'Natural grasses': 45, 'Agricultural grasses': 1, 'Coniferous': 12, 1.1: 10, (1, 3, 2): 3, 45: 'Natural grasses', 'Greenhouse': 20, 'Reed': 786}


## Removing a item in dictionary

###### * Removal of an item with a given key is called “popping the item.”

In [97]:
landcover.pop("Reed")

786

In [111]:
print(landcover)

{'Natural grasses': 45, 'Agricultural grasses': 1, 'Coniferous': 12, 1.1: 10, (1, 3, 2): 3, 45: 'Natural grasses', 'Greenhouse': 20, 'Reed': 786}


## Deletion of single item:

In [118]:
del landcover["Agricultural grasses"]
#print(landcover)

In [121]:
landcover.pop("Reed")

786

In [120]:
landcover["Greenhouse"] = None

In [123]:
print(landcover)

{'Natural grasses': None, 'Coniferous': 12, 1.1: 10, (1, 3, 2): 3, 45: 'Natural grasses', 'Greenhouse': None}


In [125]:
print(landcover["Greenhouse"])

None


In [114]:
a = None
type(a)

NoneType

## Removal of all items:

In [53]:
landcover.clear()
#print(landcover)

In [54]:
print(landcover)

{}


## Vectors or rasters as dictionaries

    - Vector or raster files can be seen as dense matrices or as dictionaries.
    
    - Storage of all values in memory may consume substantial resources, 
    
    - Not a wise choice when a significant percentage of the data is not needed Solution:
    
        * Store only the useful values

        * Make use of a sparse matrix


## Rasters or Matrices as dictionaries

##### We only need to keep the positions of the non-zero values and write them down

### That is:
    * Row 0, Col 3, Value 1
    * Row 2, Col 1, Value 2
    * Row 4, Col 3, Value 3
    
Which gives:

matrix = {(0, 3):1, (2, 1): 2, (4, 3): 3}


### Creation of a sparse matrix from a dense matrix:

In [127]:
['Hi']*5

['Hi', 'Hi', 'Hi', 'Hi', 'Hi']

In [141]:
dense_matrix = [[0]*1000, [0]*1000, [0]*1000, [0]*1000, [0]*1000]
dense_matrix[0][3] = 1
dense_matrix[2][1] = 2
dense_matrix[4][3] = 3

In [142]:
print(np.array(dense_matrix))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [143]:
import numpy as np
np.array(dense_matrix).__sizeof__()

20128

In [145]:
sparse_matrix = {}

for i in range(5):
    for j in range(1000):
        if dense_matrix[i][j] != 0:
            key = (i,j)
            value = dense_matrix[i][j]
            sparse_matrix[key]= value
            
            

In [146]:
print(sparse_matrix)

{(0, 3): 1, (2, 1): 2, (4, 3): 3}


In [147]:
sparse_matrix

{(0, 3): 1, (2, 1): 2, (4, 3): 3}

In [148]:
sparse_matrix.__sizeof__()

216

# Summary:
    * A dictionary is a data structure that stores key:value pairs, thus, it maps keys to values
    * These pairs are ordered (python 3.7)
    * The keys held in a dictionary are immutable, but their associated values are modifiable
    * The methods keys(), values() and items() allow the iteration over and viewing of the dictionary content

# 6 & 7. Operators and Conditonals

### Contents
    1. Logical operators, and comparison operators
    2. Numeric Operator (Add, Subtract, Multiplication, Division, Modulo, Floor Division, Exponentiation)
    3. Conditional execution (if, elif, else)


### 6.1 Equality, inequality

    * Equality operator == 
    * Inequality operator !=
    * Domains: just about anything! Range:	Boolean


In [149]:
2 = 2
#b = 5


SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (682841211.py, line 1)

In [65]:
print(1 == 1) # equal

True


In [150]:
print('hello' == 'world')

False


### 6.2 Modulo: numeric operator
    * Floor division //
    * Remainder or modulo %


In [154]:
print(7//2)

3


In [155]:
print(7%2)

1


In [ ]:
# Is x even?

In [157]:
# find even number 
x = 5
print(x % 2 == 0)

False


### the even test

In [71]:
print(0%2)

0


In [72]:
print(1%2)

1


In [73]:
print(2%2)

0


In [74]:
print(3%2)

1


In [75]:
print(4%2)

0


## Comparisons

    The operators <, <=, >=, and > only work if the input domains are ordered!

In [158]:
print (2 < 5) 

True


In [159]:
print('hello' > 'world')

False


## 7. Conditional Statement

### 7.1 Conditional execution

    - Suppose we want to print some text in case x is greater than zero.
    - Python has a special statement for cases like these. It is called the if statement


In [163]:
x = 0

if x > 0:
    print("x is possitive")
else:
    print("x is negative")

x is negative


## syntax

    if boolean_expression: 
        statements 1
    else: 
        statements 2
        
    • If the expression is True, then the first body of statements is executed
    • If the expression is False, then the second body of statements is executed
    • Normal processing proceeds afterwards


## 7.2 Nested if statements

    
### syntax

    if boolean_expression: 
        statements 1
    else: 
        if boolean_expression: 
            statements 2
        else: 
            statements 3
            

    Yes, but what if x is zero?

In [164]:
x = 23

if x > 0:
    print( 'x is positive')
else: 
    if x < 0:
        print( 'x is negative' )
    else:
        print( 'x is zero' )


x is positive


## 7.3 Chained conditionals

    Suppose we have numbered the days of the week and we want to map the number to a string:
    •	0 → 'Monday'
    •	1 → 'Tuesday'
    •	2 → 'Wednesday'
    •	and so on ...


### lets try with nested conditionals

In [84]:
n = 10

if n == 0:
    print("Monday")

else:
    if n == 1:
        print("Tuesday")
    else:
        if n== 2:
            print("Wednesday")
        else:
            if n == 3:
                print("Thursday")
            else:
                if n == 4:
                    print("Friday")
                else:
                    if n == 5:
                        print("Saturday")
                    else: 
                        if n == 6:
                            print("Sunday")
                        else:
                            print("Error!")

Error!


# Chained conditionals

    Chained conditionals syntax,
    
        - if boolean expression1 : 
            statements1
        - elif boolean expresion2 :
            statements2
        - else: 
            statementsN

    •	The IF statement body of the first expressionthat evaluates to True is executed
    •	Otherwise, the statements of the else clause at end.


In [169]:
n = 0

if n == 0:
  print("Monday")
   print("")
elif n == 1:
  print("Tuesday")
elif n == 2:
    print("Wednesday")
elif n == 3:
    print("Thursday")
elif n == 4:
    print("Friday")
elif n == 5:
    print("Saturday")
elif n == 6:
    print("Sunday")
else:
    print("Error!")

IndentationError: unexpected indent (2866741381.py, line 5)

## Summary

    • Modulo
    • Boolean expressions
    • Conditional execution if/elif/else


In [ ]:
print("hi")

# 8. Iterations
    - So far, we have implicitly assumed that a task is done just once …
    - In real life, repeated tasks are everywhere.


For instance:

    • Reading all lines of a CSV file and operating on them
    • Intersecting a collection of polygons
    • Calculating the buffer area around a set of points
    • Determining a regression line using the least squares method
    • Connecting to a database to retrieve data records from a table
    • Checking whether polygons in a shapefile are geometrically valid 
    • Retrieving data from a citizen science portal
    • Operating on a raster data set with a 3x3 kernel window


## Iterations

    - The repetition of a task over multiple elements is called iteration
    - Iteration is performed in a statements that we call a loop

In Python, you can use two types of loops:
    
    •The for loop
    •The while loop
    
    Normally, the task at hand will determine which of the two is the more appropriate.


## 8.1 The while loop

    * A while loop uses the following syntax:
        - while condition : body_of_statements

    * The body of statements (indented, obviously) will be repeated as long as the condition continues to evaluate to true. These statements code for the “taskper-element.”

    * While loops are used for cases when one cannot predict how often the taskper-element will need to be executed.

    * Good code ensures that eventually the condition becomes false, when there is nothing to be done anymore, for instance because there are no more elements to be handled.
    
 
#### The skeleton of a while is:

    while boolean_expression == True:
    statement #1 statement #2
    ...
    statement #N



In [86]:
#The simplest while loop is:
count = 0 
while count < 10: 
    print(count) 
    count += 1


0
1
2
3
4
5
6
7
8
9


### The while loop
    A simple while loop that prints the numbers starting at 1, until we find a nonprime number.

#### Its structure is typical of while loops:

    i = 0 # initialization
    while i < 100 : # (non-)termination condition
        if is_prime(i) is False: # statements (ie, task for the 
            i = i + 1 # element)
        else: 
            print(i)
            i = i + 1 # progress step

###### Variable i controls the progress through the loop, it is called the loop variable


### While loop order of progress
    One obviously can also count down:


In [89]:
i = 10 
while i > 0: 
    print(i) 
    i = i - 1

#We can wrap this in a function
   

10
9
8
7
6
5
4
3
2
1


In [92]:
def cound_down(n):
    i = 10
    while i > 0:
        print(i)
        i = i-1
        
    print("Boom!")
    
cound_down(10)

10
9
8
7
6
5
4
3
2
1
Boom!


#### Breaking the while loop
    We can stop the iterations with a break statement


In [93]:
i = 1
while True:
    print(i)
    if i >= 10:
        break
    i = i + 1

1
2
3
4
5
6
7
8
9
10


###### However, it is better to avoid breaks

In [94]:
i = 1
while i <= 10:
    print(i)
    i = i + 1

1
2
3
4
5
6
7
8
9
10


##### Skipping an element inside the while loop
    We can skip an iteration step with the continue statement


In [100]:
i = 0
while i < 9: 
    i = i + 1 
    if i==5 or i==7:
        continue                                                      
    else:
        print(i, "*", end="")
        
print(i+1)


1 *2 *3 *4 *6 *8 *9 *10


Normally, print() puts a newline character behind what it is printing.  
With the end="…" clause used, it ends the printed string with whatever is in … position instead.

### While iteration over a list
    We can iterate over lists, which is a common programming practice:



In [101]:
fruits = ["orange", "watermelon", "lemon", "coconut"] 
i = 0
while i < len(fruits):
    print(fruits[i], end=" ") 
    i = i + 1

orange watermelon lemon coconut 

    Observe the subtle use of end=" ".
    Also observe that in this case we know upfront how often we will iterate (namely, len(fruits) times).  
    In such cases, a for loop is usually the better coding choice.  (See later.)

### Populating a container with while
    We can populate lists

In [103]:
twenty_even_numbers = [ ] 
i = 0 
while i < 40:
    twenty_even_numbers.append(i) 
    i = i + 2
    
print(twenty_even_numbers)

#While does the job again, but a choice to use a for loop is recommended.

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]


## 8.2 The for loop

    * The for loop has the following syntax:
        - for variable in sequence : 
            body_of_statements
            
    * The variable value iterates over the complete sequence (which can be a string, a list, a tuple, or any other type of container) and assumes the value of its successive elements.
    
    * Good code 
        - makes use of the variable in the body_of_statements.
        - uses the for loop in cases when upfront we know how often the body_of_statements will be executed for an element.
        
    * This is a common coding mechanism and you can use continue also in for loops.


### The for loop
    An example with strings:

In [105]:
for char in "Hello world!": 
    print(char)

H
e
l
l
o
 
w
o
r
l
d
!


### Another example with strings:

In [108]:
my_string = "Can you reverse this?"
result = "" 
for char in my_string:
    result = char + result 
    
print(result)
    
#?siht esrever uoy naC
#Observe that here only one print statement is executed.

?siht esrever uoy naC


### The for loop 

    An example with list:
   

In [109]:
name = ["john", "jane", "bob", "alice"]
for i in sorted(name):
    print(str(i).capitalize())

Alice
Bob
Jane
John


# Steering the for loop

    * We can finetune the scope of action with range():
        for i in range(…) :
    * It is used as: range([start], stop, [step]) All arguments are integer.
    
    * start is optional and defaults to 0; step is also optional (defaults to 1)
    
    * The range() function gives us an iterator object, this is something magical over which you can iterate.  
        - With list(range(…)) 
   
you will see the list of elements that the iterator gives you. start is a member of the iterator but stop is (just) not: 


In [110]:
list(range(1,3)) == [1, 2]

True

In [113]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [114]:
print(list(range(2, 8))) 

[2, 3, 4, 5, 6, 7]


In [115]:
print(list(range(0, 12, 2))) 

[0, 2, 4, 6, 8, 10]


### Using range() in the for loop

    With range(), you can iterate over a list as you wish:


In [170]:
fruits = [ "orange", "watermelon", "lemon", "coconut", "pineapple", "banana","pomegranate", "kiwi","grapes", "apricot" ]

for fruit_index in range(0, 10, 2):                                  
    print(fruits[fruit_index])

orange
lemon
pineapple
pomegranate
grapes


In [171]:
#What is the expected output?

In [172]:
#How would you print a list of fruits at even positions with a text length shorter than the position number?

In [123]:
short_fruit = []
fruits = [ "orange", "watermelon", "lemon", "coconut", "pineapple", "banana","pomegranate", "kiwi","grapes", "apricot" ]
for fruit_index in range(0, 10, 2):
    if len(fruits[fruit_index]) < fruit_index:
        short_fruit.append(fruits[fruit_index]) 
        print(short_fruit)


['grapes']


## 8.3 Iteration over n-dimentional data structures 

    how to iterate over, for instance, a two dimentional data structures



In [183]:
m  = sum([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [186]:
sum(m[2])

24

In [176]:
rows = 3
cols = 3
the_sum = 0

In [182]:
for i in range(rows):
    for j in range(cols):
        print(f"i:{i}, j:{j}")
        the_sum = the_sum + m[i][j]
        
print(f"the sum is: {the_sum}")

i:0, j:0
i:0, j:1
i:0, j:2
i:1, j:0
i:1, j:1
i:1, j:2
i:2, j:0
i:2, j:1
i:2, j:2
the sum is: 45


#### Nested Iteration: within the over rows, we iterate over columns.
    
#### observer the use of +=, which  is expected as "plus and becomes"

### Summary

    • We use iterations for repetitive tasks
    
    • In Python, iterations are done with for and while loops
    
    • While loop is used typically when one cannot quite foresee when the process will end.
    
    • For loop is used typically when the number of steps is known upfront, for instance to access elements of a sequence
    
    • Nested loops are useful to iterate over N-dimensional data structures, for instance where lists are nested inside a list.
 