# 9. Function

    A function in Python is a block of code that can be executed repeatedly with different inputs. Functions allow you to organize your code, make it reusable and readable.

### There are two types of functions in Python:

    1. Built-in Functions: Functions that are built into Python, such as print(), len(), etc.

In [2]:
print(len("Hello, World!")) # output - 12

13


### 
    2. User-defined Functions: Functions created by the user, to perform specific tasks.

    Normal Functions: Functions that perform a specific task and return a value.

In [3]:
def my_first_function(name):
    print("Hello " + name)
    
my_first_function("vijay") # output - Hello vijay

Hello vijay


### Function return a single value

In [4]:
# return single value

def add(tm, em, mm, sm, ssm):
    total = tm + em + mm + sm + ssm
    return total

tamil_mark = 100
english_mark = 95
maths_mark = 67
science_mark = 87
social_science_mark = 90

mark_total = add(tamil_mark, english_mark, maths_mark, science_mark, social_science_mark)
print(mark_total)

439


### Calling the function with arbitary value

In [5]:
# arbitary arguments

def join_names(*v):
    result = v[0] + v[1]
    return result

fname = 'manoj '
sname = 'prabhakar'
mname = join_names(fname, sname)
print(f"name: {mname}")
print(type(mname))

name: manoj prabhakar
<class 'str'>


### Function with keyword argumens

In [6]:
# keyword argumens

def join_first_and_last_name(first_name, second_name):
    result = first_name + second_name
    return result

mname = join_first_and_last_name(first_name='manoj ', second_name='prabhakar')
print(mname)

manoj prabhakar


### Function arbitary keyword arguments

In [7]:
def join_first_and_last_name(**names):
    result = names["first_name"] + names["second_name"]
    return result

mname = join_first_and_last_name(first_name='manoj ', second_name='prabhakar')
print(mname)

manoj prabhakar


### Function with default parameters

    - In Python, you can specify default values for function parameters, which can be used if no value is passed for that parameter. 
    
    - This is done by assigning a default value to the parameter in the function definition.

In [10]:
def greet(name, message="Hello"):
    print(message + " " + name)

greet("Mahesh")

Hello Mahesh


In [7]:
greet("Alex", "Hi")

Hi Alex


### Assignment - 10: function

    Create a function to calculate the area of a circle.
    Create another function to calculate the circumference of a circle.
    Call both functions and print the results for a circle with a radius of 5.

# 10. Files, csv files and Python

    Objectives
        
        After this lecture, students will be able to:
                * Work with files and directories.
                * Write and read text files.
                
                
                
        What is a file?
        
        - Files store data - text, numbers, binary encoded data…
        - Data can be written to and read from files
        - Files can be stored in different locations: a local hard-disk, a usb drive, a disk on the network, and …
        - More remotely on the internet, reachable through a URL.  
        - Sometimes one will need to search programmatically for files, on a local disk, or on the internet.


## File path
    A location of a file is called a file path. It is denoted as a string.

    String literals use \ as an escape character. This allows the inclusion of non-standard characters in a string. E.g., \\ stands for a single backslash:
    
        'C:\\ITC\\ProgrammingSkills\\'
        'C:/ITC/ProgrammingSkills/'
        
    Raw string literals, flagged by an r, do not give \ a special meaning: r'C:\ITC\ProgrammingSkills'
    
    Raw string literals,
    
        - treat backslashes as literal characters
        - cannot end with a backslash
        - flag b denotes a byte string literal


## Directory as file container

    - Every file is held in some directory.  The location of a file is determined by the file path. 
        "File path = directory path + file name".

    - Can be an absolute path
        'C:/ITC/ProgrammingSkills/myfile.txt'
        
    - Or a relative path
        '../GISModelling/myotherfile.txt'
        
    - '.’ is current directory, and '..' is parent directory.
    
    Pragmatics: use of relative paths is good coding style as it allows to place your program anywhere on disk and continue to operate locally.


## File path types

    * Absolute path
    
        - PROs: the location is exact
        - CONs: a change in the directory structure will change the absolute path
        
    * Relative path
    
        - PROs: moving the working directory will not create problems (if all the files are in the same directory or its children)
        - CONs: the exact location is unknown
        
        
        
    * Current working directory
    
        - The current working directory (CWD) is the directory where the program was started from.
        - Relative paths are relative to the CWD.


## Module os to work with the operating system
Use the os module to determine the current working directory
(cwd) or to change it import 

In [1]:
import os

In [2]:
os.getcwd()

'C:\\Users\\Muthukumar\\Downloads\\NLP\\Python_Basic_NoteBook'

In [23]:
# change directory
#os.chdir('C:\\Users\\Muthukumar\\Downloads\\NLP')
os.chdir('C:\\Users\\Muthukumar\\Downloads\\NLP\\Python_Basic_NoteBook')

In [24]:
os.getcwd()

'C:\\Users\\Muthukumar\\Downloads\\NLP\\Python_Basic_NoteBook'

## Module os

In [6]:
# what is the absolute path? 
os.path.abspath('basic_of_python_session-3.ipynb')

'C:\\Users\\Muthukumar\\Downloads\\NLP\\basic_of_python_session-3.ipynb'

In [9]:
# does the directory/file exist? 
os.path.exists('C:\\Users\\Muthukumar\\Downloads\\NLP1')

False

In [12]:
# is this a directory? os.path.isfile( 'myfile.txt' )
os.path.isdir('C:\\Users\\Muthukumar\\Downloads\\NLP')

True

In [13]:
os.path.isfile('C:\\Users\\Muthukumar\\Downloads\\NLP\\basic_of_python_session-3.ipynb')

False

In [15]:
# list of files and directories
os.listdir('C:\\Users\\Muthukumar\\Downloads\\NLP') 

['.ipynb_checkpoints',
 'appln-test',
 'apply-swapped(y_and_h_hat)-in-linear_regression - Copy.ipynb',
 'apply-swapped(y_and_h_hat)-in-linear_regression.ipynb',
 'assignments',
 'Bi-variate-logistic-regresssion.ipynb',
 'header_files',
 'hourly-status',
 'imdb_labelled - orgdataset.txt',
 'imdb_labelled-dataset-model-training-without-preprocessing-NLP.ipynb',
 'imdb_labelled.txt',
 'l1-test.ipynb',
 'linear-handson-09012023.ipynb',
 'Linear-logistic-reg-code',
 'Linear-Regression-08012023.ipynb',
 'linear-regression-09012023.ipynb',
 'Linear-Regression-Model-Training-and-Testing.ipynb',
 'linear_regression',
 'Logistic-regression',
 'Logistic-Regression-Model-Training-and-Testing.ipynb',
 'logistic-regression-try-09012023 - Copy.ipynb',
 'Logitic-Regression-08012023.ipynb',
 'MLP-3-Layer-(2h).ipynb',
 'MLP-3-Layer.ipynb',
 'mpqa-sentiment-lexicon.ipynb',
 'neg_lex.txt',
 'pos_lex.txt',
 'Python_Basic_NoteBook',
 'random_variable-(y-y_hat)-linear-regression.ipynb',
 'random_variable-(y_

In [19]:
# get (sub)files and (sub)directories
os.walk('C:\\Users\\Muthukumar\\Downloads\\NLP')

<generator object _walk at 0x000001ED9CE70E40>

In [20]:
for rootdirectory, dirs, files in os.walk('C:\\Users\\Muthukumar\\Downloads\\NLP'): 
    print ( rootdirectory, dirs, files )

C:\Users\Muthukumar\Downloads\NLP ['.ipynb_checkpoints', 'appln-test', 'assignments', 'header_files', 'hourly-status', 'Linear-logistic-reg-code', 'linear_regression', 'Logistic-regression', 'Python_Basic_NoteBook', 'subjectivity_clues_hltemnlp05', 'Unittesting_report', 'Univariate-Logistic-Regression', 'Univariate-Logistic-Regression - Copy', '__MACOSX'] ['apply-swapped(y_and_h_hat)-in-linear_regression - Copy.ipynb', 'apply-swapped(y_and_h_hat)-in-linear_regression.ipynb', 'Bi-variate-logistic-regresssion.ipynb', 'imdb_labelled - orgdataset.txt', 'imdb_labelled-dataset-model-training-without-preprocessing-NLP.ipynb', 'imdb_labelled.txt', 'l1-test.ipynb', 'linear-handson-09012023.ipynb', 'Linear-Regression-08012023.ipynb', 'linear-regression-09012023.ipynb', 'Linear-Regression-Model-Training-and-Testing.ipynb', 'Logistic-Regression-Model-Training-and-Testing.ipynb', 'logistic-regression-try-09012023 - Copy.ipynb', 'Logitic-Regression-08012023.ipynb', 'MLP-3-Layer-(2h).ipynb', 'MLP-3-L

C:\Users\Muthukumar\Downloads\NLP\header_files\__pycache__ [] ['Bivariate_Logistic_Regression.cpython-310.pyc', 'Bivariate_Logistic_Regression_more_slope_and_input.cpython-310.pyc', 'Linear_Regression.cpython-310.pyc', 'Linear_Regression_L1.cpython-310.pyc', 'Linear_Regression_L2.cpython-310.pyc', 'Multivariate_Logistic_Regression.cpython-310.pyc', 'test.cpython-310.pyc', 'Univariate_Logistic_Regression.cpython-310.pyc', 'Univariate_Logistic_Regression_L1.cpython-310.pyc', 'Univariate_Logistic_Regression_L2.cpython-310.pyc']
C:\Users\Muthukumar\Downloads\NLP\hourly-status [] ['hourly-status.xlsx', '~$hourly-status.xlsx']
C:\Users\Muthukumar\Downloads\NLP\Linear-logistic-reg-code ['.ipynb_checkpoints'] ['Untitled.ipynb']
C:\Users\Muthukumar\Downloads\NLP\Linear-logistic-reg-code\.ipynb_checkpoints [] ['Untitled-checkpoint.ipynb']
C:\Users\Muthukumar\Downloads\NLP\linear_regression [] ['Linear_Regression.py', 'linear_regression_class_test.ipynb']
C:\Users\Muthukumar\Downloads\NLP\Logisti

## Step 1: Open the file
        
        * A file must be opened before reading, updating, deleting data
        * You can read from the beginning of the file to the end, or you can skip some parts
        * When you finish, you need to close the file.
        * Pragmatics: always close files as a good programming practice.


## File types
    
    Different kinds of file have different types of content:
    
        * Text files (.txt, .csv, .html, .xml …)
        * Binary files (.doc, .png, .exe …) We will focus on text files.  
        * Special case are .csv (comma-separated values) which hold one record of data per line. It is a data exchange workhorse file type.
        * Web harvesting techniques fetch .html or .xml files by url and interpret the contents.


## Text files

    A text file contains printable characters, tabs and spaces, organized into lines that are separated by newline characters printable chars: a-z; A-Z; 0-9, '~!@#,;:', …
    
	- newline: '\n' (line break, line terminator, end-of-line (EOL) )
	- whitespace characters: ' ', '\t'


## How to open a file for write actions?
In the program, create a Python file object f as follows:


In [31]:
f = open('myfile.txt', 'w')

### 
    - By default, this is a text file.  Object f "points to that file."

    - The second parameter is called mode. Mode 'w': we will write to the file. 

    - Use mode 'x' for exclusive creation  # check file existence


In [32]:
print(f) #  encoding='cp1252' - by default, the local character encoding is used

<_io.TextIOWrapper name='myfile.txt' mode='w' encoding='cp1252'>


## Performing file write actions

In [33]:
f.write( 'I write something\n' )  # Note we are adding a newline

18

In [34]:
f.write( 'I write something else\n' )

23

In [35]:
f.close()  # Always close the files

In [37]:
f.write( 'I am writing again' ) #ValueError: I/O operation on closed file

ValueError: I/O operation on closed file.

## How to write multiple lines?
    
    Writing multiple lines

In [38]:
f = open('myfile.txt', 'w')

In [39]:
lines = [ 'I write something\n', 'I write something else\n' ]

In [40]:
f.writelines( lines )

In [41]:
f.close()

In [42]:
print(f)

<_io.TextIOWrapper name='myfile.txt' mode='w' encoding='cp1252'>


## How to append to a file 

    Open a file object, and use mode 'a' f = 

In [46]:
f = open('myfile.txt', 'a')

In [47]:
print(f)

<_io.TextIOWrapper name='myfile.txt' mode='a' encoding='cp1252'>


In [48]:
f.write( 'I append this line of text.' )

27

In [50]:
f.close() # If the file does not exist, a new file will be created

## How to open a file for read actions

    Open a file object with mode 'r' f 

In [75]:
f = open('myfile.txt', 'r')

In [60]:
print( f )

<_io.TextIOWrapper name='myfile.txt' mode='r' encoding='cp1252'>


### 
If you do not specify a mode, you will by default operate in mode ‘r’
 

## How to read a text file

In [61]:
text = f.read() # read the whole file

In [62]:
print(text)

I write something
I write something else
I append this line of text.


## How to read character strings

In [77]:
f.seek( 0 ) # go back to the beginning of the file

0

In [78]:
text = f.read(18)	# read 18 characters 
print( text )

I write something



In [79]:
text = f.read(32)	# read another 32 characters 
print(text)

I write something else
I append 


In [80]:
text = f.read(5) # read 5 more

In [81]:
print(text) # nothing read and nothing to print

this 


## The use of iteration in file operations You can use iteration:

In [12]:
f = open( 'myfile.txt', 'r' ) 

for line in f:
    print(line, end = ' ')


## Stripping strings
    
    Stripping a string takes away the whitespace characters at the start and at the end


In [13]:
f.seek(0)

0

In [14]:
text = f.readlines()	# reads all the lines and creates a list print( text )

In [15]:
for i in range( len(text) ):
    text[ i ] = text[ i ].strip() #delete leading and trailing whitespaces


In [16]:
print( text )

[]


## File operations: truncation

    If you want to read and write without truncation use the mode 'r+'


In [90]:
f = open( 'myfile.txt', 'r+' ) # content will not be deleted


    If you want to read and write with truncation use the mode 'w+'


In [92]:
f = open( 'myfile.txt', 'w+' )	# content will be deleted

## File operation modes

mode - Meaning

    'r' - Open for reading
    'w' - Open for writting, truncating the file first
    'x' - open for exclusive creation, failing when the file already exists
    'a' - Open for writting, appending to the end of the file  if it  exists
    't' -  text mode (default)
    'b' - binary mode
    '+' - open a disk for updating (reading and writing)


the default mode is 'rt'

    'w+t' or 'w+b' opens and truncates the file
    'r+t' or 'r+b' opens the file without truncation 


## Make a file copy going by character

In [94]:
def copy_file(oldFile, newFile): 
    f1 = open( oldFile, 'r' ) 
    f2 = open( newFile, 'w' ) 
    text = f1.read( 1 ) 
    while text != '':
        f2.write(text) 
        text = f1.read( 1 )
        f2.close() 
        f1.close() 
        copy_file( 'myfile.txt', 'mynewfile.txt' )


In [95]:
# Note: Python module shutils offers several high-level functions to operate on files.  Including copying files.

## Make a file copy working by lines

In [96]:
def copy_file_byline(old_file, new_file):
    f1 = open(old_file, 'r')
    f2 = open(new_file, 'w')
    
    for line in f1:
        f2.write(line)
        
    f2.close()
    f1.close()
    
copy_file_byline('myfile.txt', 'mynewfile.txt')

## Make a file copy in one go

In [98]:
def greedy_copy_file(oldFile, newFile): 
    
    f1 = open( oldFile, 'r' ) 
    f2 = open( newFile, 'w' ) 
    text = f1.read() 
    
    if not text == '':
        f2.write( text ) 
    
    f2.close() 
    f1.close() 
    
greedy_copy_file( 'myfile.txt', 'mynewfile2.txt')

## Obtaining a file through a url

In [100]:
import urllib.request as r
f = r.urlopen('http://www.textfiles.com/adventure/impossiblemission2.sol') 
f.read()


b'\n             "IMPOSSIBLE MISSION II" - HINTS, TIPS, SOLUTION (?)\n            By Jaromir Krol - "Jerry King" - jaromirk@kki.net.pl\n                  http://www.kki.net.pl/jaromirk/c64joke/\n\n\n Elvin  Atombender,  the  evil genius, is  at  it  again. What? Destroying the\n world, of course. And it\'s up to you to stop him. (Actually, the storyline in\n the  manual is a nice read, so take a look at it at Project 64!). All right -\n Elvin  lives  in a complex of nine towers.  You must search the eight of them\n one  by  one, and finally get access  to  Elvin\'s control room, hidden in the\n last  tower.  To get to that room, you will  need a melody code - this is why\n you have the mini recorder at your disposal! :) Read on for more.\n\n I   recommend   playing  this  game  with   an  emulator  that  has  freezing\n capabilities,  or  with a program/card which  can  do it (Game Wizard, Action\n Replay...).  This  way,  you can freeze  before  dangerous situations, and if\n somethin

## Detection and count of characters in a file

In [103]:
def count_char(filePath): 
    f = open(filePath)
    story = f.read().upper().replace('\n', '').replace('\t' , '').replace(' ','') 
    f.close()
    chars = [ ]	# list for the characters found
    counts = [ ] 
    for c in story:
        if c in chars:
            i = chars.index(c) 
            counts[i] = counts[i] + 1
        else:
            chars.append(c) 
            counts.append(1)
    
    for i in range(len(chars)): 
        print(chars[i], counts[i])	# list for the counts


## Detection and count of characters by dictionary

In [106]:
def count_char(filePath): 
    f = open(filePath)
    story = f.read().upper(). replace('\n', '').replace('\t', '').replace(' ', '') 
    f.close()
        
    chars = { }	# dictionary in which (key:value) will be (character:count) 
    for c in story: 
        if c in chars:
            chars[c] = chars[c] + 1 
        else:
            chars[c] = 1
    
    for c in chars: 
        print (c, chars[c])


## Reading a data .csv file
    
    The csv module implements classes to read and write tabular data in CSV format.  This is a very simple yet useful format for data science and data exchange.

    The csv module’s reader and writer objects read and write sequences of data
    
    DictReader and DictWriter classes are used to convert data from .csv to dictionaries, and vice versa

    Pragmatics: look at example code that uses Dict… at trustworthy sites on the internet 


## Reading a data .csv file

In [112]:
import csv 

f = open('C:\\Users\\Muthukumar\\Downloads\\FinallTraining-Nalgond_Cotton_Points-16122022.csv') 

reader = csv.reader(f) 

for line in reader: 
    print( line )
    
f.close()


['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30', 'label']
['-17.27114091', '-20.37268141', '-18.94357971', '-16.06975486', '-14.26176284', '-16.25983816', '-20.39186638', '-17.98374218', '-15.57561797', '-14.48734608', '-11.59780472', '-14.59522765', '-11.81034817', '-11.14393114', '-18.08989698', '-9.307428296', '-7.979278572', '-6.12506982', '-2.732493402', '-0.480770858', '-5.586126301', '-9.371862409', '-6.889252727', '-4.406643045', '-6.585123107', '-6.573554943', '-8.312870242', '-7.056916546', '-6.236629795', '-6.930985792', '1']
['-25.03030368', '-23.66324172', '-20.64455223', '-16.21540529', '-19.50114411', '-22.62406915', '-18.72376779', '-16.86541499', '-15.00706219', '-14.72103538', '-12.90900687', '-14.69796673', '-15.41477773', '-15.48319934', '-14.13461134', '-15.07075913', '-14.20765479', '-9.903810426', '-9.07628782', 

## Other delimiters in a .csv file

    Though they are called comma-separated, .csv files may use a different delimiter such as tab or ; or |

In [113]:
f = open('C:\\Users\\Muthukumar\\Downloads\\FinallTraining-Nalgond_Cotton_Points-16122022.csv')
reader = csv.reader( f ) # the default delimiter is ','

In [114]:
f = open('C:\\Users\\Muthukumar\\Downloads\\FinallTraining-Nalgond_Cotton_Points-16122022.csv') 
reader = csv.reader( f, delimiter = ';' )

In [115]:
f = open('C:\\Users\\Muthukumar\\Downloads\\FinallTraining-Nalgond_Cotton_Points-16122022.csv') 
reader = csv.reader( f, delimiter = '\t')

## Dictreader .csv operation

In [119]:
import csv

f = open('C:\\Users\\Muthukumar\\Downloads\\FinallTraining-Nalgond_Cotton_Points-16122022.csv')

reader = csv.DictReader(f, fieldnames=['F1','F2','F3']) 

for line in reader:
    print(line)
f.close()


{'F1': 'F1', 'F2': 'F2', 'F3': 'F3', None: ['F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30', 'label']}
{'F1': '-17.27114091', 'F2': '-20.37268141', 'F3': '-18.94357971', None: ['-16.06975486', '-14.26176284', '-16.25983816', '-20.39186638', '-17.98374218', '-15.57561797', '-14.48734608', '-11.59780472', '-14.59522765', '-11.81034817', '-11.14393114', '-18.08989698', '-9.307428296', '-7.979278572', '-6.12506982', '-2.732493402', '-0.480770858', '-5.586126301', '-9.371862409', '-6.889252727', '-4.406643045', '-6.585123107', '-6.573554943', '-8.312870242', '-7.056916546', '-6.236629795', '-6.930985792', '1']}
{'F1': '-25.03030368', 'F2': '-23.66324172', 'F3': '-20.64455223', None: ['-16.21540529', '-19.50114411', '-22.62406915', '-18.72376779', '-16.86541499', '-15.00706219', '-14.72103538', '-12.90900687', '-14.69796673', '-15.41477773', '-15.48319934', '-

## Binary files

    * You can write and read files in binary mode using ‘wb’ and ‘rb’. But this is out of scope of this lecture.
    
    * If you use binary mode when you read (or write) a file, things won’t be much different. You are still able to read a number of bytes (basically much the same as characters), and perform other operations associated with text files.

    * Geospatial vector and raster data is shared in binary files also.  All image data is principally in binary files; a common vector data format that is binary is the (Esri) shapefile.  A shapefile is actually not one file, but a package of four or five files.


## Summary
    
    * Files and directories.
    * Opening text files: reading, writing and append text.
    * Reading online text.
    * Reading CSV files.

# 11. The use of NumPy

    Python and NumPy revisited


# Python and dynamic typing

Python is well-known for its ease of use

    ▪ One of the characteristics: DYNAMIC TYPING
    
    ▪ In contrast to strongly typed languages, in Python we do not need to define the type of a variable
    
    ▪ But standard Python implementation is written in C
    
    ▪ A C integer is a label for a memory position
    
    ▪ A Python integer is pointer to an object with additional information
    
    ▪ Additional information allows Python to be dynamic
    
    ▪ This additional information result in additional cost, in particular for complex data structures

## Python, dynamic typing, and Python List

    ▪ Python List
    
        ▪ Each item is complete Python object
        
        ▪ If items in the list are the same, then a lot of redundant data
        
        ▪ Algorithms need to deal with the additional information of every object in the list 
        
        ▪ Not Efficient
        
        
    ▪ Python answer: Fixed-Type Arrays in Python
    
    ▪ A better solution: NumPy array, which is Fixed-Type and 

## Numpy array creation

    We assume throughout these slides that we have
    import numpy as np
    
    Array creation
    
    ▪ Conversion from another Python data structure: list or tuple np.array( [ 1, 2, 3] ) or np.array( ( 6.05673, 52.56220 ) ) 
    
    ▪ Note: NumPy is contrained to arrays of the same type! NumPy will UPCAST if possible
    array( [ 3.14, 2, 3] 

In [120]:
import numpy as np

## • Array generator functions

In [121]:
np.array([1,2,3])

array([1, 2, 3])

In [124]:
np.arange(6) # half-open interval [0, 6⟩
# numpy.arange([start, ]stop, [step, ]dtype=None)

array([0, 1, 2, 3, 4, 5])

In [126]:
np.linspace(0, 1, 12) # closed interval with number of steps
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [127]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [128]:
np.ones((2,3), dtype=float) 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [129]:
np.full((4,2), 5) # Create a 4×2 array filled with 3.14

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

### Other array generators: np.random, np.normal, np.eye, np.empty

# NumPy array  attributes

    Four important attributes,
    
    1. ndim
    2. shape
    3. size
    4. dtype
    


In [131]:
x1 = np.random.randint(5, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(2,3,4))

x1, x2, x3

(array([2, 3, 0, 2, 4, 1]),
 array([[5, 0, 3, 1],
        [3, 4, 8, 3],
        [3, 1, 4, 8]]),
 array([[[9, 5, 2, 1],
         [6, 3, 4, 7],
         [0, 6, 1, 0]],
 
        [[3, 1, 7, 2],
         [7, 3, 6, 0],
         [2, 1, 7, 7]]]))

In [135]:
print("x1 ndim: ", x1.ndim)
print("x1 shape: ", x1.shape)
print("x1 size: ", x1.size)

print("x2 ndim: ", x2.ndim)
print("x2 shape: ", x2.shape)
print("x2 size: ", x2.size)

print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x1 ndim:  1
x1 shape:  (6,)
x1 size:  6
x2 ndim:  2
x2 shape:  (3, 4)
x2 size:  12
x3 ndim:  3
x3 shape:  (2, 3, 4)
x3 size:  24


## Array Indexing, Slicing, and Reshaping

### Array indexing

       ▪ Quite similar with Python’s standard list indexing
       
        ▪ Takes place between [ and ]
        
        ▪ Various expression types can be between the brackets
        
        ▪ Is allowed in left-hand and right-hand expression of an assignment
        
        arrA[ ] = arrB[ ]
        
        
        Single element indexing
        
            ▪ arrA[4] is the 5th element as it is 0-based
            
            ▪ arrA[-2] is the one but last element


## Observe this … in value

In [153]:
arrA = np.arange(8)
arrA

array([0, 1, 2, 3, 4, 5, 6, 7])

In [160]:
arrA.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [162]:
arrA[1,0]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [166]:
arrA = arrA.reshape(2,4)
arrA

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [168]:
arrA[1,0]

4

In [169]:
arrA[1,0] = 9
arrA

array([[0, 1, 2, 3],
       [9, 5, 6, 7]])

In [170]:
arrA[1]

array([9, 5, 6, 7])

In [ ]:
arrA[1] = [4,5,6]

#Traceback (most recent call last): File "<stdin>", line 1, in <module>
#ValueError: cannot copy sequence with size 3 to array axis with dimension 4

In [173]:
arrA[1] = [4,5,6,2]
arrA[1]

array([4, 5, 6, 2])

In [174]:
arrA[:,1] = [10,12] 

In [175]:
arrA

array([[ 0, 10,  2,  3],
       [ 4, 12,  6,  2]])

## Slicing

    ▪ In any dimension, a slice is a possibly empty list of indices
    
    ▪ Normal notation is n : k
    standing for the list of indices from n to k, n inclusive and k exclusive.
    
    ▪ If we leave out n, it gets replaced by 0 (read it as "from start")
    If we leave out k, it gets replaced by the highest index value possible 
    (read it as "to end")
    
    ▪ Not often used but allowed is also a stride value (aka step size), with 
    notation n : k : s
    standing for the list of indices going from n to k with step s.
    
    ▪ If we leave out s, we leave out : also, and use 1 as step value.
    
    ▪ Slices and strides allow you to "cut through the data cube."
    
    ▪ Cf. arange's three parameters

## slicing

In [178]:
x = np.arange(10, 30)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [179]:
x[::-1] # all elements, reversed

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [180]:
x[::2] # every other elemen

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

## ▪ Multidimensional

In [181]:
x = np.arange(0, 24).reshape((4,6))
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [182]:
x[:2,:3]

array([[0, 1, 2],
       [6, 7, 8]])

In [183]:
x[:,1] # Second column

array([ 1,  7, 13, 19])

In [184]:
x[2,:] # Third row

array([12, 13, 14, 15, 16, 17])

In [185]:
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [186]:
x_slice = x[0, 4:]

In [187]:
x_slice[0] = 100

In [188]:
x_slice[1] = 200

In [189]:
print(x)


[[  0   1   2   3 100 200]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]]


## Changing the shape of an array

    ▪ reshape function
    ▪ Add an axis with np.newaxis (this adds no values, just reshapes)


In [191]:
xx = np.arange(5)
xx

array([0, 1, 2, 3, 4])

In [192]:
xx[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [193]:
xx

array([0, 1, 2, 3, 4])

## Concatenation

    Joining arrays
    
        ▪ Three important functions
        ▪ np.concatenate()
        ▪ np.vstack()
        ▪ np.hstack()

In [195]:
x = np.array([4,5,6])
y = np.array([8,9,10])
np.concatenate([x, y])

array([ 4,  5,  6,  8,  9, 10])

## Joining arrays

    ▪ Concatenation along other axes


In [196]:
z = np.array([[11,22,33],
              [99,88,77]])

In [197]:
np.concatenate([z, z]) # concatenate along the first axis

array([[11, 22, 33],
       [99, 88, 77],
       [11, 22, 33],
       [99, 88, 77]])

In [198]:
np.concatenate([z, z], axis = 1)

array([[11, 22, 33, 11, 22, 33],
       [99, 88, 77, 99, 88, 77]])

## Universal Functions

    ▪ The importance of NumPy is related to its vectorized operations
    
    ▪ Using Python List, operations on arrays need to be done through loop
    
        e.g., imagine you want to compute the reciprocals of every element in a list, or you want 
        to multiply every element by a constant value.

    ▪ Looping over Python List is very slow, due to the dynamic nature of the Python language
    
        ▪ Type checking 
        ▪ Function dispatches
        ▪ …
        
    ▪ Solution
    
        ▪ NumPy provides a convenient interface over several precompiled array operations
        
        ▪ This precompiled array operations, known as vectorized operations, are accessible 
        via NumPy ufuncs
        
        ▪ Extremely fast, particularly for big arrays
        
        ▪ Loops are not

## UFuncs
    ▪ We apply Ufuncs to an array
    ▪ The function operates at element level
    ▪ With Python List, if we want to calculate the reciprocals of an array:


In [199]:
x = [2., 3., 5., 12., 30.]

reciprocals = []

for e in x:
    reciprocals.append(1. / e)

print(reciprocals)

[0.5, 0.3333333333333333, 0.2, 0.08333333333333333, 0.03333333333333333]


    ▪ With Ufuncs:

In [200]:
x = np.array([2., 3., 5., 12., 30.], dtype=np.float)

reciprocals = 1. / x

print(reciprocals)

[0.5        0.33333333 0.2        0.08333333 0.03333333]


C:\Users\Muthukumar\AppData\Local\Temp\ipykernel_4572\225567666.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([2., 3., 5., 12., 30.], dtype=np.float)


## UFuncs

In [201]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

    We can directly apply Python arithmetic operators as 
    UFuncs to NumPy arrays

In [202]:
print(.3 * x + x**2 + 12)

[12.  13.3 16.6 21.9 29.2]


    For each of these arithmetic operators there is a 
    function counterpart implemented in numpy 

## Other UFuncs

    ▪ Trigonometric functions
    
    ▪ Hyperbolic functions
    
    ▪ Exponents and logarithms
    
    ▪ Rounding
    
    ▪ …
    
    ▪ See https://numpy.org/doc/stable/reference/routines.math.html for a 
    complete list of available functions

## Aggregations

    ▪ Simple aggregation functions:
    
        - np.sum()
        
        - np.min()
        
        - np.max()
        
    ▪ Multidimensional aggregations
    
        ▪ E.g., how to calculate the maximum value of 
            each row or column in a matrix

In [204]:
x = np.arange(1, 16).reshape((5, 3))
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [205]:
print("Sum of columns: ", x.sum(axis=0))

Sum of columns:  [35 40 45]


In [206]:
print("Sum of rows: ", x.sum(axis=1))

Sum of rows:  [ 6 15 24 33 42]


## List of NumPy aggregation functions

    • There are also a NaN-safe version of each of these functions (except for np.all and np.any)
    
        • E.g., np.nansum()
        
    • NaN: Not a number
    
    • functions - Description
        - np.mean() - compute the arithmetic mean along the specified axis.
        - np.std() - compute the standard deviation along the specified axis.
        - np.var() - compute the varience along the specified axis.
        - np.sum() - sum of array elements over a given axus.
        - np.prod() - Return the product of array elements over a given axis.
        - np.cusum() - return the cumulative product of elements along a given axis
        - np.cumprod() - return the cumulative product of elements along a given axis.
        - np.min(), np.max() - return the minimum/ maximum of an array or minimum along an axis.
        - np.argmin(), np.argmax() - return the indices of the minimum/maximum values along an axis.
        - np.all() - test whether all array elements along a given axis evaluate to True.
        - np.any() - test whether any array elements along a given axis evaluate to True.

## Broadcasting

    ▪ In NumPy, for arrays of the same size, binary operations perform on an element-by-element basis:
   

In [207]:
x = np.array([10, 20, 30])
y = np.array([1, 2, 3])

print(x + y)

[11 22 33]


# 
    ▪ What happens if we apply a binary operation on two array with different size?

In [209]:
a = np.arange(3)
print(a)

[0 1 2]


In [211]:
b = np.arange(3)[:, np.newaxis]
print(b)

[[0]
 [1]
 [2]]


In [212]:
print(a + b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


## Cascading
    
    ▪ NumPy tries to stretch and broadcast one of the array to match the shape of the other array. Then it applies the binary operation on the output arrays.

In [215]:
a = np.array([[0]*3, [10]*3, [20]*3, [30]*3])
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [216]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [220]:
print(a + b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


## Comparisons and Boolean Logic

### Comparison operators on NumPy arrays
    
    ▪ Applying a comparison operator on NumPy arrays result in an array of 
    Boolean values (True/False) 
    
    

In [221]:
x = np.array([7, 8, 13, 80, 12, 1, 5])
print(x > 14)

[False False False  True False False False]


# 
    ▪ Comparison operators: ==, !=, <, <=, >, >=

## Boolean masks

    Expression myArr [ myBoolArr ] uses another type of indexing with rather different semantics. The myBoolArr must have same shape or be broadcastable to myArr.
    
     ▪ Result is a one-dim array with myArr values found at positions where myBoolArr has value True. Sequence is row-major.

     ▪ Common example: myArr [ 2<myArr & myArr<10 ]

     ▪ Result is actually multidimensional when dim(myArr)>dim(myBoolArr), essentially as if you wrote myArr [ myBoolArr, … ] 

    If Boolean masks are used in assignment statements the rhs must be shaped as lhs or be broadcastable to it:
        myArr [ myBoolArr ] = rhs
        
    ▪ One often uses the lhs as part of the rhs to ensure shape is correct. The selectivity of myBoolArr is otherwise hard to determine, unless one can rely on broadcasting.

## Some good references to read

    ▪ We only covered the most important aspects of NumPy
    
    ▪ For more information about NumPy functionalities see:x
        ▪ https://numpy.org/devdocs/user/quickstart.html
        ▪ https://www.w3schools.com/python/numpy_intro.asp
        ▪ https://www.tutorialspoint.com/numpy/index.htm
        
    ▪ Extended version of the slides was uploaded on Canvas.

## List Comphrehension

    List comprehension is a concise way to create a list in Python. It allows you to create a list by specifying an expression and a for loop to iterate over some iterable (such as a range, list, or tuple).

    The general syntax of list comprehension is:
    
        [expression for item in iterable if condition]
        
        
    where:

        - 'expression' is the operation or function to be applied to each item in the iterable.
        - 'item' is the variable name used to represent each item in the iterable.
        - 'iterable' is the object that is being iterated over.
        - 'if condition' is an optional condition that can be used to filter the items in the iterable.
        
    List comprehension is used for its simplicity, conciseness, and readability, and it can be used for various purposes, including creating new lists, filtering lists, mapping values, and more.

        Here are some examples of list comprehension in Python:

        1. Creating a list of squares of numbers from 1 to 10:


In [222]:
squares = [x*x for x in range(1, 11)]
print(squares)
# Output: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


# 

    2. Filtering a list to include only even numbers:

In [223]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_numbers = [x for x in numbers if x % 2 == 0]
print(even_numbers)
# Output: [2, 4, 6, 8, 10]


[2, 4, 6, 8, 10]



    3. Creating a list of tuples from two separate lists:

In [224]:
names = ['Alice', 'Bob', 'Charlie']
ages = [25, 30, 35]
people = [(name, age) for name, age in zip(names, ages)]
print(people)
# Output: [('Alice', 25), ('Bob', 30), ('Charlie', 35)]


[('Alice', 25), ('Bob', 30), ('Charlie', 35)]


    4. Creating a list of lowercase letters in a string:

In [225]:
text = "Hello, World!"
letters = [char.lower() for char in text if char.isalpha()]
print(letters)
# Output: ['h', 'e', 'l', 'l', 'o', 'w', 'o', 'r', 'l', 'd']


['h', 'e', 'l', 'l', 'o', 'w', 'o', 'r', 'l', 'd']


These are just a few examples of what you can achieve with list comprehension in Python. 

## Types,

    In Python, there are three types of list comprehension:
    
        1. Basic list comprehension: This type of list comprehension generates a new list by applying an expression to each item in an iterable. The general syntax for basic list comprehension is: 
        
                            new_list = [expression for item in iterable]
                            
           For example, to create a list of the first 10 even numbers, you can use the following basic list comprehension:


In [226]:
even_numbers = [x for x in range(2, 21, 2)]
print(even_numbers)
# Output: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


        2. List comprehension with filter: This type of list comprehension generates a new list by applying an expression to each item in an iterable that satisfies a given condition. The general syntax for list comprehension with filter is:
        
            new_list = [expression for item in iterable if condition]
            
        For example, to create a list of the squares of the even numbers from 1 to 10, you can use the following list comprehension with filter:

In [228]:
squares_of_even_numbers = [x**2 for x in range(1, 11) if x % 2 == 0]
print(squares_of_even_numbers)
# Output: [4, 16, 36, 64, 100]


[4, 16, 36, 64, 100]



    3. Nested list comprehension: This type of list comprehension generates a new list by using one or more for loops inside another for loop. The general syntax for nested list comprehension is:
    
        new_list = [expression for item1 in iterable1 for item2 in iterable2 ... for itemN in iterableN]

        For example, to create a list of tuples that contains all possible combinations of two lists, you can use the following nested list comprehension:

In [229]:
list1 = ['a', 'b', 'c']
list2 = [1, 2, 3]
combinations = [(x, y) for x in list1 for y in list2]
print(combinations)
# Output: [('a', 1), ('a', 2), ('a', 3), ('b', 1), ('b', 2), ('b', 3), ('c', 1), ('c', 2), ('c', 3)]


[('a', 1), ('a', 2), ('a', 3), ('b', 1), ('b', 2), ('b', 3), ('c', 1), ('c', 2), ('c', 3)]


These are the three types of list comprehension in Python.

## Thank You!!! 